### ISSUE TITLE
Dateset Generation code

### ISSUE THREAD

**Issue by wpraas** [kairess/fingerprint_recognition#1]
Hi
I have a question regarding generation of numpy arrays as .npz and .npy i.e. image dataset and their labels dataset.
In this kernel you loaded already converted dataset, I have also tried to convert and do this step which is not present in the current kernel but my numpy arrays are different from yours. Can you please share code of this sep as well or put the file in the github separately.?

**Comment by kairess** [comment]
Hey, @wpraas 

I added preprocess code as below:

https://github.com/kairess/fingerprint_recognition/blob/master/preprocess.ipynb

Thanks!

**Comment by wpraas** [comment]
instead of two functions you can also use this optimized code`####Pre processing####
def get_label(str):
    label = []
    #my_str = "SOCOFing/Real\9__M_Right_thumb_finger.BMP"
    my_str = str
    #id split
    my_str = re.split("\W+", my_str)
    mystr1 = my_str[2].split("__")
#    print(mystr1[0])
    label.append(int(mystr1[0]))
    
    
    mystr2 = mystr1[1].split("_")
#    print(mystr2)
    
    #M or F split
    if mystr2[0] == 'M':
        mystr2[0] = '1'
        label.append(int(mystr2[0]))
    elif mystr2[0] == 'F':
        mystr2[0] = '0'
        label.append(int(mystr2[0]))
    
    # Right hand or left hand split
    if mystr2[1] == 'Right':
        mystr2[1] = '1'
        label.append(int(mystr2[1]))
    if mystr2[1] == 'Left':
        mystr2[1] = '0'
        label.append(int(mystr2[1]))
    
    # Fingername
    if mystr2[2] == 'thumb':
        mystr2[2] = '0'
        label.append(int(mystr2[2]))
    elif mystr2[2] == 'index':
        mystr2[2] = '1'
        label.append(int(mystr2[2]))
    
    elif mystr2[2] == 'middle':
        mystr2[2] = '2'
        label.append(int(mystr2[2]))
    elif mystr2[2] == 'ring':
        mystr2[2] = '3'
        label.append(int(mystr2[2]))
    elif mystr2[2] == 'little':
        mystr2[2] = '4'
        label.append(int(mystr2[2]))
    return label
   #return np.array(label, dtype=np.uint16)`

**Comment by wpraas** [comment]
Hi,
Thanks for your prompt response. The preprocessing code creates only .npy files

`x_real = np.load('dataset/x_real.npz')['data']`
Reference: Filename: train.ipynb In [3]:

It creates .npz file with another key data. How it is created?

Do I need to save x_real.npy to x_real.npz?
Kindly elaborate or fix this issue.

**Comment by kairess** [comment]
@wpraas 

Yes, use np.savez_compressed() to save data to .npz

**Comment by wpraas** [comment]
I have used 
np.savez_compressed('SOCOFing/partial/dataset/x_real.npz', data = imgs)

But after loading I got a 3D array whereas when I load your dataset it shows 4D array, Can you tell me what is missing?

Example,
4D
`print(x_real.shape)`
6000, 90, 90, 1

3D
`print(x_real.shape)`
6000, 90, 90

**Comment by kairess** [comment]
You can use np.expand_dims() to imgs variable.

`imgs = np.expand_dims(imgs, axis=-1)`

I lost final preprocessing code. Sorry for that.
